### ISSUE TITLE
Python error

### ISSUE THREAD

**Issue by GViana0** [grainseed/monitask#3]
Hi, 
I'm getting this error message when I start collecting areas

--------------------------------------------------------------------------------------------------------
2024-02-08T19:46:39     WARNING    Traceback (most recent call last):
              File "C:\Users/IDEA/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\monitask-master\maptool.py", line 249, in canvasReleaseEvent
              self.setWorkingExtent(imgcrs_point)
              File "C:\Users/IDEA/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\monitask-master\maptool.py", line 394, in setWorkingExtent
              self.refreshWorkingImage()
              File "C:\Users/IDEA/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\monitask-master\maptool.py", line 449, in refreshWorkingImage
              self.segany.reset_image()
             AttributeError: 'NoneType' object has no attribute 'reset_image'

![image](https://github.com/grainseed/monitask/assets/159495419/b1153e9d-4fbd-44ec-b267-a99f17aec2ad)

**Comment by GViana0** [comment]
I try the mobile version of the QGIS-V3.30 compressed package, but gave another error..



![image](https://github.com/grainseed/monitask/assets/159495419/8bcb4a26-2d1e-447b-8811-1ce36543e7db)
